INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'small', 3, 1);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'medium', 4, 1);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'large', 5, 1);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'small', 3, 1);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'medium', 4, 1);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'large', 5, 1);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'small', 3, 2);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'medium', 4, 2);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'large', 5, 2);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'small', 3, 2);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'medium', 4, 2);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'large', 5, 2);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'small', 3, 3);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'medium', 4, 3);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'large', 5, 3);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'small', 3, 3);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'medium', 4, 3);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'large', 5, 3);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'small', 3, 4);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'medium', 4, 4);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'large', 5, 4);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'small', 3, 4);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'medium', 4, 4);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('dark', 'large', 5, 4);
INSERT INTO menu_item_options (option_category, name,s price, menu_item_id) VALUES ('italian', 'small', 3, 5);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'medium', 4, 5);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'large', 5, 5);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'small', 3, 5);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'medium', 4, 5);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'large', 5, 5);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'small', 3, 6);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'medium', 4, 6);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'large', 5, 6);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'small', 3, 6);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'medium', 4, 6);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'large', 5, 6);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'small', 3, 7);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'medium', 4, 7);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'large', 5, 7);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'small', 3, 7);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'medium', 4, 7);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'large', 5, 7);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'small', 3, 8);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'medium', 4, 8);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('italian', 'large', 5, 8);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'small', 3, 8);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'medium', 4, 8);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'large', 5, 8);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Size', 'small', 4.5, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Size', 'medium', 5.5, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('dark', 'large', 5, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Whole Milk', 0, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Skim Milk', 0, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Almond Milk', 1, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Size', 'large', 6, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Soy Milk', 1, 9);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Oat Milk', 1, 9);


-- INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Size', 'small', 5, 10);
-- INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Size', 'medium', 5.99, 10);
-- INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Size', 'large', 6.99, 10);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Whole Milk', 0, 10);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Skim Milk', 0, 10);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Almond Milk', 1, 10);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Soy Milk', 1, 10);
INSERT INTO menu_item_options (option_category, name, price, menu_item_id) VALUES ('Milk', 'Oat Milk', 1, 10);

