CREATE TABLE menu_item_options (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  size VARCHAR(5) NOT NULL,
  price INTEGER NOT NULL,
  menu_item_id INTEGER REFERENCES menu_items ON DELETE CASCADE
);
